# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://gilles-zerah.github.io/learn_sentences/"

git_url = "https://github.com/gilles-zerah/learn_sentences/tree/master/"

def custom_doc_links(name): return None
